version: '3.4'

services:
  mssqldb:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=a123456!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_server:/var/opt/mssql

  faceio.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
volumes:
  sql_server:
