version: '3.4'

services:
  mssqldb:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=a123456!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_server:/var/opt/mssql

volumes:
  sql_server: