version: '3.4'

services:
  mssqldb:
    container_name: system.mssql.db
    image: mcr.microsoft.com/mssql/server:2019-latest
  faceio.api:
    image: ${DOCKER_REGISTRY-}faceioapi
    build:
      context: .
      dockerfile: src/Api/FaceIO.Api/Dockerfile

