CREATE TABLE [dbo].[Face]
(
	[Id]			INT IDENTITY (1, 1)		NOT NULL,
	[Uid]			UNIQUEIDENTIFIER		NOT NULL,
	[CreatedOn]		SMALLDATETIME			NOT NULL,
	[DeletedOn]		SMALLDATETIME			NULL,
	[PersonFk]		INT						NOT NULL,
	[FileName]		NVARCHAR(500)			NOT NULL,
	CONSTRAINT [PK_Face] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_Face_Person] FOREIGN KEY ([PersonFk]) REFERENCES [dbo].[Person] ([Id])
)

GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_Face_Uid]
	ON [dbo].[Face] ([Uid] ASC) WHERE([DeletedOn] IS NULL);